version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "kevalpatel2106"
    schedule:
      interval: "daily"
    labels:
      - "PR type > dependencies"
  - package-ecosystem: "gradle"
    directory: "/"
    reviewers:
      - "kevalpatel2106"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "PR type > dependencies"
