changelog:
  exclude:
    labels:
      - ignore-in-changelog
    authors:
      - dependabot
      - gradle-update-robot
  categories:
    - title: New Features ðŸŽ‰
      labels:
        - Change type > new-feature
    - title: Bugfixes ðŸ› 
      labels:
        - Change type > bug
    - title: Documentation ðŸ“
      labels:
        - Change type > documentation
    - title: Automation ðŸ¤–
      labels:
        - Change type > automation
    - title: Other Changes
      labels:
        - "*"
