changelog:
  exclude:
    labels:
      - ignore-in-changelog
    authors:
      - dependabot
      - gradle-update-robot
  categories:
    - title: New Features and enhanchements ðŸŽ‰
      labels:
        - PR type > new-feature
        - PR type > enhanchement
    - title: Bugfixes ðŸ› 
      labels:
        - Pr type > bug
    - title: Documentation ðŸ“
      labels:
        - PR type > documentation
    - title: Tehchnical ðŸ¤–
      labels:
        - PR type > automation
        - PR type > refactoring
    - title: Other Changes
      labels:
        - "*"
