name: PR workflow

on:
  pull_request:
    paths-ignore:
      - '*/.creds/**'
      - .idea/**
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_code_analysis.yml@main

  security:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_security.yml@main

  test:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_test.yml@main
    secrets:
      AVD_CACHE_VERSION: ${{secrets.AVD_CACHE_VERSION}}

  build:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_build.yml@main

  house-keeping:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: PR labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
          sync-labels: true
      - name: PR size check
        uses: kkohtaka/gh-actions-pr-size@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-run-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: [ quality, test, build ]
    steps:
      - name: Save the PR URL in an artifact to be reused by automerge workflow run
        env:
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
        run: echo $PULL_REQUEST_URL > pull_request_url.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pull_request_url
          path: ./pull_request_url.txt
