name: PR workflow

on:
  pull_request:
    paths-ignore:
      - '*/.creds/**'
      - .idea/**
      - LICENSE

jobs:
  quality:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_code_analysis.yml@main
    secrets:
      CACHE_VERSION: ${{secrets.CACHE_VERSION}}

  test:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_tests.yml@main
    secrets:
      CACHE_VERSION: ${{secrets.CACHE_VERSION}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  build:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_build.yml@main
    secrets:
      CACHE_VERSION: ${{secrets.CACHE_VERSION}}

  house-keeping:
    runs-on: ubuntu-latest
    steps:
      - name: PR labeler
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/pull_request_labeler_filters.yml"
          sync-labels: true
      - name: PR size check
        uses: ookami-kb/gh-pr-size-watcher@v1.1.0
        with:
          githubToken: "${{ secrets.GITHUB_TOKEN }}"
          warningSize: 500
          warningMessage: More than **500 lines** added. Consider splitting into smaller PRs.
          excludeTitle: '[SKIP_SIZE_CHECK]'
          excludePaths: |
            **.md
            **.json
            **.yml
            .idea/**

  check-run-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: [quality, test, build]
    steps:
      - name: Save the PR URL in an artifact to be reused by automerge workflow run
        env:
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
        run: echo $PULL_REQUEST_URL > pull_request_url.txt
      - uses: actions/upload-artifact@v2
        with:
          name: pull_request_url
          path: ./pull_request_url.txt
