name: Main branch workflow

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  quality:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_code_analysis.yml@main

  security:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_security.yml@main

  test:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_test.yml@main
    needs: [quality, security]
    secrets:
      AVD_CACHE_VERSION: ${{secrets.AVD_CACHE_VERSION}}

  build:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_build.yml@main
    needs: [test]
    secrets:
      UPLOAD_KEYSTORE_BASE64: ${{secrets.UPLOAD_KEY_KEYSTORE_BASE64}}
      UPLOAD_KEYSTORE_ALIAS: ${{secrets.UPLOAD_KEY_KEYSTORE_ALIAS}}
      UPLOAD_KEYSTORE_PASSWORD: ${{secrets.UPLOAD_KEY_KEYSTORE_PASSWORD}}
      UPLOAD_ALIAS_PASSWORD: ${{secrets.UPLOAD_KEY_ALIAS_PASSWORD}}

  deploy:
    uses: kevalpatel2106/pocket-ci/.github/workflows/reuse_deploy.yml@main
    needs: [build]
    if: ${{ github.repository == 'kevalpatel2106/pocket-ci' }}
    secrets:
      PLAY_SERVICE_ACCOUNT_JSON: ${{secrets.PLAY_SERVICE_ACCOUNT_JSON}}
