name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    name: Update Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: Change type > dependencies
          repo-token: ${{ secrets.PAT_GITHUB }}
