name: Code check

on:
  workflow_call:

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run detekt
        run: ./gradlew detekt --scan --stacktrace
      - name: Upload results Artifact
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: detekt-report
          path: |
            **/build/reports/detekt/**/*
          if-no-files-found: error

  lint:
    name: android lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Run lint
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: |
            app:lintRelease
            --stacktrace
      - name: Generate annotations from lint report
        if: success() || failure()
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: '**/build/reports/lint-results-*.xml'
        continue-on-error: true
      - name: Upload lint report
        if: success() || failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: lint-report
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error

  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint check
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: yamllint-config.yml
