name: Code check

on:
  workflow_call:

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run detekt
        run: ./gradlew detekt --scan --stacktrace
      - name: Upload results Artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detekt-report
          path: |
            **/build/reports/detekt/**/*
          if-no-files-found: error

  lint:
    name: android lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Run lint
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: |
            app:lintRelease
            --stacktrace
      - name: Generate annotations from lint report
        if: success() || failure()
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: '**/build/reports/lint-results-*.xml'
        continue-on-error: true
      - name: Upload lint report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.47.1/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/
      - name: Lint with ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-report.xml
      - name: Generate annotations from ktlint report
        uses: yutailang0119/action-ktlint@v3
        if: failure()
        with:
          report-path: build/ktlint-report.xml
        continue-on-error: true
      - name: Upload results Artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ktlint-report
          path: |
            **/build/ktlint-report.xml
          if-no-files-found: error

  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint check
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: yamllint-config.yml
