name: Test

on:
  workflow_call:
    secrets:
      AVD_CACHE_VERSION:
        required: true

jobs:
  unit-test:
    name: unit tests
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Run Unit tests
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: |
            jacocoTestReport
            --stacktrace
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
      - name: Upload test results Artifact
        uses: actions/upload-artifact@v3.1.2
        if: success() || failure()
        with:
          name: unit-test-report
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
          if-no-files-found: warn

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
    strategy:
      fail-fast: false  # Allow tests to continue on other devices if they fail on one device.
      matrix:
        arch: [ x86_64 ]
        target: [ google_apis ]
        channel: [ stable ]
        api-level:
          - 27
          - 29
          - 33
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: AVD cache
        uses: actions/cache@v3.3.1
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ secrets.AVD_CACHE_VERSION }}
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          disable-animations: true
          disable-spellchecker: true
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          disable-animations: true
          disable-spellchecker: true
          ram-size: 4096M
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedAndroidTest mergeAndroidReports
      - name: Upload test results Artifact
        uses: actions/upload-artifact@v3.1.2
        if: success() || failure()
        with:
          name: android-test-report
          path: |
            ./build/androidTest-results/*
          if-no-files-found: warn
