name: Build

on:
  workflow_call:
    secrets:
      UPLOAD_KEYSTORE_BASE64:
        required: false   # Only for main branch
      UPLOAD_KEYSTORE_ALIAS:
        required: false   # Only for main branch
      UPLOAD_KEYSTORE_PASSWORD:
        required: false   # Only for main branch
      UPLOAD_ALIAS_PASSWORD:
        required: false   # Only for main branch

jobs:
  debug:
    name: Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build debug APK
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            :app:assembleDebug
            --stacktrace
      - name: Upload debug APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/*.apk
      - name: Upload reports
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: report-apk-debug
          path: |
            build/reports/*
          if-no-files-found: warn

  release:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build release APK (signed with upload key)
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            :app:assembleRelease
            --stacktrace
      - uses: r0adkll/sign-android-release@v1.0.4
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        id: sign_app
        name: Sign release APK
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
          alias: ${{ secrets.UPLOAD_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.UPLOAD_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.0"
      - name: Upload signed APK
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apk-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload un signed APK
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apk-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned-aligned.apk
      - name: Upload reports
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: report-apk-release
          path: |
            build/reports/*
          if-no-files-found: warn

  aab:
    name: AAB to release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build release bundle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            :app:bundleRelease
            --stacktrace
      - uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        name: Sign release AAB
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
          alias: ${{ secrets.UPLOAD_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.UPLOAD_ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.0"
      - name: Upload AAB
        uses: actions/upload-artifact@v3.1.2
        with:
          name: bundle-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload mapping
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mapping-bundle-release
          path: app/build/outputs/mapping/release/mapping.txt
      - name: Upload reports
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: report-bundle-release
          path: |
            build/reports/*
          if-no-files-found: warn
