name: Code security check

on:
  workflow_call:

jobs:
  dependency-submission:
    name: Gradle dependency submission
    runs-on: ubuntu-latest
    permissions:
      # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Submit dependencies
        uses: mikepenz/gradle-dependency-submission@v0.8.5
        with:
          gradle-build-module: ":app"

  gradle-validation:
    name: Gradle wrapper validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: gradle/wrapper-validation-action@v1

  codeql:
    timeout-minutes: 30
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "java" ]

    steps:
      - uses: actions/checkout@v3.3.0

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      # Auto build doesn't work when using gradle version catalog in ./build.gradle
      # More on the bug: https://github.com/github/codeql-action/issues/1417#issuecomment-1446028805
      - name: Manual build
        if: matrix.language == 'java'
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: |
            assembleRelease
            --no-daemon

      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go).
      - name: Autobuild
        if: matrix.language != 'java'
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
    name: New dependencies review
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Dependency Review
        uses: actions/dependency-review-action@v3.0.3
        with:
          config-file: './.github/dependency-review-config.yml'
