name: Weekly workflow

on:
  schedule:
    - cron: "0 0 * * 6"   # At 00:00 on Saturday.
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    name: Update Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.18
        with:
          labels: Change type > dependencies
          repo-token: ${{ secrets.PAT_GITHUB }}

    baseline-profiles:
      runs-on: macos-latest
    timeout-minutes: 45
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
    strategy:
      fail-fast: false  # Allow tests to continue on other devices if they fail on one device.
      matrix:
        api-level:
          - 33
      steps:
        - uses: actions/checkout@v3.4.0
        - uses: actions/setup-java@v3.10.0
          with:
            distribution: 'adopt'
            java-version: 17
        - name: AVD cache
          uses: actions/cache@v3.3.1
          id: avd-cache
          with:
            path: |
              ~/.android/avd/*
              ~/.android/adb*
            key: avd-${{ matrix.api-level }}-${{ secrets.AVD_CACHE_VERSION }}
        - name: Create AVD and generate snapshot for caching
          if: steps.avd-cache.outputs.cache-hit != 'true'
          uses: reactivecircus/android-emulator-runner@v2.28.0
          with:
            api-level: ${{ matrix.api-level }}
            force-avd-creation: false
            disable-animations: true
            avd-name: test
            disable-spellchecker: true
            ram-size: 4096M
            emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            script: echo "Generated AVD snapshot for caching."
        - name: Run baseline profile generator
          uses: reactivecircus/android-emulator-runner@v2.28.0
          with:
            api-level: ${{ matrix.api-level }}
            force-avd-creation: false
            disable-animations: true
            avd-name: test
            disable-spellchecker: true
            ram-size: 4096M
            emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            script: ./gradlew :benchmark-macro:connectedBenchmarkAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.kevalpatel2106.coreTest.filter.BaselineProfileGenerator
        - name: Upload baseline profiles
          uses: actions/upload-artifact@v3.1.2
          if: success()
          with:
            name: baseline-profiles
            path: |
              ./benchmark-macro/build/outputs/connected_android_test_additional_output/benchmark/connected/*/*.txt
            if-no-files-found: warn
        - name: Upload test results Artifact
          uses: actions/upload-artifact@v3.1.2
          if: success() || failure()
          with:
            name: baseline-profile-test-report
            path: |
              ./build/androidTest-results/*
            if-no-files-found: warn
